name: Container Apps Deploy

on:
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: Build and deploy Container App
        uses: azure/container-app-deploy-action@main
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: ca6dd75f61c0acr
          containerAppName: test-actions
          resourceGroup: dotnet-conf-2022
